language: perl

perl:
  - "5.28"
  - "5.22"

before_install:
  cpanm -n Devel::Cover::Report::Coveralls

script:
  perl Makefile.PL && make thirdparty && make && cover -test -report coveralls +ignore example +ignore thirdparty
